apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: employees
      app.kubernetes.io/component: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: employees
        app.kubernetes.io/component: frontend  
    spec:
      containers:
      - name: webapp
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:app.v0.1
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.7"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123"  
