apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 3 
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: backend
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:db.v0.1
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: db_pass123
        - name: DBHOST
          value: mysqldb
