apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
#  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:app.v0.1
        ports:
        - containerPort: 8080
        env:
        - name: DBPORT
          value: "3306"
        - name: DBHOST
          value: mysqldb