apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
spec:
  containers:
  - name: webapp-container
    image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:app.v0.1
    env:
    - name: DBHOST
      value: "10.244.0.19"
    - name: DBPORT
      value: "3306"
    - name: DBPWD
      value: "db_pass123"
    ports:
    - containerPort: 8080
