apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: frontend
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:app.v0.1
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "10.244.0.22"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "db_pass123"
