apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  externalName: mysql.prod.svc.cluster.local  
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app.kubernetes.io/name: employees
    app.kubernetes.io/component: frontend
