apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: webapp
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/component: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/component: webapp
    spec:
      containers:
      - name: webapp
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:app.v0.1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
