apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: myapp
    app.kubernetes.io/component: mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myapp
      app.kubernetes.io/component: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myapp
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: 070752711409.dkr.ecr.us-east-1.amazonaws.com/clo835-repo:db.v0.1
        args:
          - --bind_ip
          - 0.0.0.0
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3306
